version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: security_dashboard
      POSTGRES_USER: dashboard_user
      POSTGRES_PASSWORD: secure-postgres-password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashboard_user -d security_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  security-dashboard:
    build: .
    environment:
      DATABASE_URL: postgresql://dashboard_user:secure-postgres-password@postgres:5432/security_dashboard
      SESSION_SECRET: your-secret-key-here
      FLASK_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  uploads_data: